Migration CRA to VITE
Hyperfoil/Horreum pull request #1076
Opened 2024-01-09 06:59 UTC by shivam-sharma7

Vite is a build tool that aims to provide a faster and leaner development experience for modern web projects because CRA is no longer maintained

closes: #995

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

2024-01-09 07:14 UTC, shivam-sharma7 commented
I have tested it locally and build got success and vite config also working fine.

2024-01-09 10:18 UTC, shivam-sharma7 commented
@johnaohara check once again

2024-01-09 14:20 UTC, johnaohara requested changes
We also want to;

- remove `horreum-web/src/setupProxy.js` 
- we now have 2 different index.html's,  `horreum-web/index.html` & `horreum-web/public/index.html`.  We need to remove the old file `horreum-web/public/index.html` and ensure that the quarkus filter redirects to the correct index.html (https://github.com/Hyperfoil/Horreum/blob/846c9687b58950c646bed6e9189bf587da7d3460/horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/RouteFilter.java)

2024-01-09 14:56 UTC, shivam-sharma7 commented on horreum-web/vite.config.ts
> +        }
done 👍

2024-01-09 15:09 UTC, shivam-sharma7 commented
> We also want to;
> 
> * remove `horreum-web/src/setupProxy.js`

done

> * we now have 2 different index.html's,  `horreum-web/index.html` & `horreum-web/public/index.html`.  We need to remove the old file `horreum-web/public/index.html` and ensure that the quarkus filter redirects to the correct index.html (https://github.com/Hyperfoil/Horreum/blob/846c9687b58950c646bed6e9189bf587da7d3460/horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/RouteFilter.java)

WDYT? for current changes RouteFilter.. do we have to realy change?

2024-01-09 16:35 UTC, shivam-sharma7 commented on horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/RouteFilter.java
> +   private static final String[] PATH_PREFIXES = { "/q/", "/api/", "/@" };
```suggestion
   private static final String[] PATH_PREFIXES = { "/q/", "/api/", "/@" };
```

let's try this

2024-01-10 10:47 UTC, johnaohara commented
I have removed this from the 0.11 milestone.  It is not critical for the 0.11 release and we can make this change in a point release after 0.11.0

2024-01-10 11:54 UTC, shivam-sharma7 commented
@johnaohara if you thing its good then please aprrove this and resolve the conversation

2024-01-22 17:12 UTC, johnaohara approved these changes
@shivam-sharma7 this looks good to me now, please can you rebase on top of master and we can get this merged, many thanks

2024-01-23 11:48 UTC, johnaohara commented
@shivam-sharma7 do you see the node.js dev server closed when the horreum dev process is stopped? I had an orphaned node.js process still listening on port 3000 after I stopped the dev mode

2024-01-23 13:05 UTC, shivam-sharma7 commented
> @shivam-sharma7 do you see the node.js dev server closed when the horreum dev process is stopped? I had an orphaned node.js process still listening on port 3000 after I stopped the dev mode

I will take a look

2024-01-24 07:08 UTC, merged

2024-01-24 18:04 UTC, johnaohara commented
@shivam-sharma7 how did you generate `package-lock.json` for this PR? When i run `npm i` in `horreum-web` now a lot of dependencies are removed and is causing build issues with vite on windows

2024-01-25 08:34 UTC, shivam-sharma7 commented
@johnaohara Here I got build got success and in order to  generate `package-lock.json` I deleted old one and I run `npm i` in `horreum-web`
```java
on-tests\0.12-SNAPSHOT\horreum-integration-tests-0.12-SNAPSHOT-tests.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Horreum 0.12-SNAPSHOT:
[INFO]
[INFO] Horreum ............................................ SUCCESS [  1.400 s]
[INFO] horreum-api ........................................ SUCCESS [ 14.719 s]
[INFO] Horreum Client ..................................... SUCCESS [  1.233 s]
[INFO] Horreum infra - common ............................. SUCCESS [  0.533 s]
[INFO] Horreum Dev Services - Parent ...................... SUCCESS [  0.032 s]
[INFO] Horreum Dev Services - Runtime ..................... SUCCESS [  5.204 s]
[INFO] Horreum Dev Services - Deployment .................. SUCCESS [  5.614 s]
[INFO] Horreum Backend .................................... SUCCESS [02:55 min]
[INFO] Horreum Integration Tests .......................... SUCCESS [01:01 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:33 min
[INFO] Finished at: 2024-01-25T13:55:31+05:30
```