WIP: Add Collector API datastore
Hyperfoil/Horreum pull request #1703
Opened 2024-05-15 11:47 UTC by zakkak

## Fixes Issue

Closes #1109 

## Proposed Changes

This patch issues a request to the collector API to get all available data. To limit the size of returned data we allow the use of a specific `tag`, but this is still not optimal as some tags may still contain a lot of data. Ideally we would need a way to get data in batches (this might need change in the Collector API). Furthermore we should be able to only request data added since the last import when rerunning an import. 

Disclaimer: This is till WIP and not meant to be merged as is.

## Check List (Check all the applicable boxes)

- [ ] My code follows the code style of this project.
- [X] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

2024-07-03 12:22 UTC, johnaohara requested changes
One thing we need to think about is duplicated runs. As it currently works, the call to the collector api simply returns all the results for a given `tag`, each invocation will return all the data and will be uploaded into Horreum

So, we either need to be able to query the api to return a subset of the data, or we need to handle de-duplication in Horreum

2024-07-03 12:22 UTC, johnaohara commented on horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/CollectorApiDatastore.java
> +                        .uri(java.net.URI.create(jsonDatastoreConfig.url + "/api/v1/image-stats/tag/" + payload.get("tag").asText()));
should the url `path` be a separate config param, or part of the `jsonDatastoreConfig.url`, if the api changes (e.g. a version bump) then this hard-coded path will likely be no longer valid

2024-07-03 12:23 UTC, johnaohara commented
Ah, I now see this issue wrt filtering the api result: https://github.com/Karm/collector/pull/34

2024-09-13 06:34 UTC, zakkak commented
https://github.com/Karm/collector/pull/35 is now merged enabling filtering by tag, benchmark, and date range (not pushed to production yet though). So I will adapt the PR to use the new API.

2024-09-13 07:48 UTC, johnaohara commented
@zakkak excellent news.

2024-10-01 13:22 UTC, zakkak commented
@johnaohara this should now be ready for review.

2024-10-03 17:22 UTC, johnaohara approved these changes
LGTM!

2024-10-03 17:22 UTC, merged

2024-10-03 17:23 UTC, johnaohara commented
@zakkak Many thanks for your contribution!