Add machine accounts
Hyperfoil/Horreum pull request #1711
Opened 2024-05-20 12:33 UTC by barreiro

Adds a `machine` user role. 

There is a bit of mismatch as it's presented in the UI as a team role, so that it can be managed by team managers. 

Fixes #1702 .

2024-05-29 05:40 UTC, barreiro commented
added test case

2024-05-29 10:17 UTC, johnaohara commented
This PR makes changes to the UI, please can we add/modify the docs?

2024-05-29 19:19 UTC, barreiro commented
Added section to the docs with a couple screenshots :grinning:

2024-06-01 08:40 UTC, johnaohara requested changes

2024-06-02 06:22 UTC, johnaohara commented
> There is a bit of mismatch as it's presented in the UI as a team role, so that it can be managed by team managers.

I think this confuses the role logic and UI slightly, in that "Machine Account" is a "User Role", whereas we are presenting is as a "Team Role", which;

1. Means that machine accounts can be re-used / managed by multiple teams - i.e. think password reset
2. Couples the logic between user roles & team roles.

I think the logic would be simpler, we could guard against re-use and the UI would be more intuitive if under the "Machine Accounts" Tab, we have a "New Account" button that created a new "Machine Account" for a particular team

2024-06-04 10:47 UTC, barreiro commented on docs/site/content/en/docs/Concepts/core-concepts/users/index.md
> +## Bot accounts (CI)
:+1:

2024-06-04 10:48 UTC, barreiro commented on docs/site/content/en/docs/Concepts/core-concepts/users/index.md
> +Click on the red `Reset Password` button and confirm. A dialog with the new generated password appears. Copy the password and close the dilog. This is the only time the password is visible.
:+1:

2024-06-05 03:21 UTC, barreiro commented
I have revamped this PR after your comments, with the goal of improving UX.

1. Accounts are created and managed in the `Machine Accounts` tab and in there only.
2. They are not displayed in the UI as users and their roles are not mutable.
3. Because of the way they are created and managed, they are only associated with a single team.
4. Same behavior for both keycloak and database backends, meaning that machine accounts can be consistently created in different scenarios (keycloak, database or external OIDC provider).
5. Test cases now cover both backends, and ensure that these accounts can log in with Basic authentication in both cases.

When migrating between versions, this feature requires that a new `machine` base role is created in keycloak.

2024-06-06 14:44 UTC, johnaohara commented
@barreiro this looks good, final question, how do users remove team accounts?

2024-06-07 09:25 UTC, merged