Add new test service api to return label values for filter: Fixes #1767
Hyperfoil/Horreum pull request #1768
Opened 2024-06-06 21:06 UTC by johnaohara

## Fixes Issue

Fixes #1767

![image](https://github.com/Hyperfoil/Horreum/assets/959822/cbcc10a9-f0b0-46ae-b8a7-71332f429155)

2024-06-07 08:27 UTC, lampajr requested changes
Overall looks great, I added some changes that are more for simplification

2024-06-10 05:53 UTC, johnaohara commented on horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
> +                     AND (label.id IS NULL OR (TRUE AND label.filtering))
This part of the WHERE clause is not correct now, I will fix it

2024-06-10 05:55 UTC, johnaohara commented on horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
> +      if(filters == null || filters.isEmpty())
good catch, thanks

2024-06-10 06:00 UTC, johnaohara commented on horreum-web/src/domain/runs/TestDatasets.tsx
> +            .then((result: Array<any>) => result)
Thanks, have re-factored this further

2024-06-10 08:06 UTC, johnaohara commented
@lampajr please can you take another look?

2024-06-10 08:41 UTC, lampajr commented on horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
> +              .setParameter("testId", test.id);
This is actually just a simplification, it does not change the behavior so up to you :rocket:

2024-06-10 08:52 UTC, lampajr commented on horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
> +         SELECT DISTINCT COALESCE(jsonb_object_agg(label.name, lv.value), '{}'::::jsonb) AS values
As you highlighted here https://github.com/Hyperfoil/Horreum/issues/1766 I think you can use `::` and it should work as well
```suggestion
         SELECT DISTINCT COALESCE(jsonb_object_agg(label.name, lv.value), '{}'::jsonb) AS values
```

2024-06-10 11:54 UTC, johnaohara commented
@lampajr and again... ;)

2024-06-10 12:01 UTC, lampajr approved these changes
LGTM!

Thanks @johnaohara, sorry for the nit-picking :smiley:

2024-06-10 12:02 UTC, merged