Remove hardcoded test recalc timeout
Hyperfoil/Horreum pull request #2122
Opened 2024-10-23 15:47 UTC by lampajr

Follows the same change that have been done for run recal 👉🏻  https://github.com/Hyperfoil/Horreum/pull/2084

## Changes proposed

- [x] Remove the test datasets recalc timeout use case

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

2024-10-24 10:25 UTC, johnaohara requested changes
Does this PR need to be rebased on main branch to pick up changes to `mediator.sharedLock()`?

2024-10-24 10:25 UTC, johnaohara commented on horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
> +                mediator.executeBlocking(() -> mediator.withRecalculationLock(() -> {
I think we can remove the lock here.

2024-10-24 10:32 UTC, lampajr commented
> Does this PR need to be rebased on main branch to pick up changes to `mediator.sharedLock()`?

Yeah, I will need to rebase it!

2024-10-25 10:56 UTC, johnaohara approved these changes

2024-10-25 10:56 UTC, merged