Issue 2088
Hyperfoil/Horreum pull request #2223
Opened 2024-12-21 13:54 UTC by johnaohara

This is a fairly major re-factor of the `Datastore` configuration API.

It solves the following problems;

- Add Strongly Typed authentication models: `No Auth`, `Api Key` and `Username/Password`
- Add openapi discriminators for datastore authentication types
- Fixes validation for all datastores: Fixes #2088 
- UI dynamically displays auth properties based on available auth types and user selected auth type
- Add validation of authentication when updated existing datastores

2025-01-02 20:00 UTC, stalep commented on horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/CollectorApiDatastoreConfig.java
> +            if ("".equals(apiKeyAuth.apiKey)) {
I assume apiKey can never be null since it's required?

2025-01-02 20:27 UTC, barreiro requested changes
I added several comments to the code, but overall looks good.

2025-01-02 20:27 UTC, barreiro commented on horreum-web/src/domain/admin/Datastores.tsx
> +
move out of the import section

2025-01-02 20:27 UTC, barreiro commented on horreum-web/src/domain/admin/Datastores.tsx
> -            <StackItem>
fix indentation level

2025-01-03 12:26 UTC, johnaohara commented on horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/CollectorApiDatastoreConfig.java
> +            if ("".equals(apiKeyAuth.apiKey)) {
If the user has selected "api-key" as the authentication method, then the apiKey can not be empty or null. Otherwise the user should select the "none" authentication model.

However, the api is not checking for null here, just zero length string. There should also be a check for null

2025-01-03 12:27 UTC, johnaohara commented on horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/CollectorApiDatastoreConfig.java
> +                return "url must be set";
good catch

2025-01-03 12:29 UTC, johnaohara commented on horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/DatastoreType.java
> +    public class TypeConfig {
good catch

2025-01-03 12:31 UTC, johnaohara commented on horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ConfigServiceImpl.java
> +            .collect(Collectors.toList());
Definitely easier to read :)

2025-01-03 14:12 UTC, johnaohara commented on horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ConfigServiceImpl.java
> +
Done

2025-01-03 14:13 UTC, johnaohara commented on horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/CollectorApiDatastore.java
> +
done

2025-01-03 14:13 UTC, johnaohara commented on horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/CollectorApiDatastore.java
> +        HttpRequest tagsRequest = null;
done

2025-01-03 14:15 UTC, johnaohara commented on horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/CollectorApiDatastore.java
> +
I have changed this back, it was left-over from some other re-factoring that I reverted.

2025-01-03 14:16 UTC, johnaohara commented on horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/ElasticsearchDatastore.java
> +                } else if (elasticsearchDatastoreConfig.authentication instanceof PasswordAuthentication) {
thanks

2025-01-03 14:17 UTC, johnaohara commented on horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/ElasticsearchDatastore.java
> +            return datastoreConfig.validateConfig();
reverted

2025-01-03 14:19 UTC, johnaohara commented on horreum-web/src/domain/admin/datastore/ModifyDatastoreModal.tsx
> +        setAuthOptions(typeConf?.supportedAuths || [])
This helped while debugging, having a local variable on the stack to inspect. but can remove the allocation

2025-01-03 14:22 UTC, johnaohara commented on horreum-web/src/domain/admin/datastore/ModifyDatastoreModal.tsx
> +        const selectedOption: TypeConfig | undefined = dataStoreTypes.filter( optionvalue => optionvalue.enumName === value).pop()
updated

2025-01-03 14:23 UTC, johnaohara commented on horreum-web/src/domain/admin/datastore/ModifyDatastoreModal.tsx
> +        <div>
updated

2025-01-03 14:25 UTC, johnaohara commented on horreum-web/src/domain/admin/datastore/ModifyDatastoreModal.tsx
> +            <FormGroup
have added `isRequired` to the api text input

2025-01-03 14:25 UTC, johnaohara commented on horreum-web/src/domain/admin/datastore/ModifyDatastoreModal.tsx
> +                value={ (dataStore.config.authentication as UsernamePassAuth).password } //"password" in dataStore.config ? dataStore.config.password : ""}
removed comments

2025-01-03 14:29 UTC, johnaohara commented on horreum-web/src/domain/admin/Datastores.tsx
> -            <StackItem>
This refers to a line that has been removed, but I am applied auto formatting to the entire file

2025-01-06 12:00 UTC, barreiro requested changes
Added some suggestions for more cleanup on the API module

2025-01-06 12:00 UTC, barreiro commented on horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/CollectorApiDatastoreConfig.java
> +    public static final String[] auths = { NoAuth._TYPE, APIKeyAuth._TYPE };
```suggestion
```

2025-01-06 12:00 UTC, barreiro commented on horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/CollectorApiDatastoreConfig.java
> +            if ("".equals(apiKeyAuth.apiKey) || apiKeyAuth.apiKey == null) {
```suggestion
            if (apiKeyAuth.apiKey == null || apiKeyAuth.apiKey.isEmpty()) {
```

2025-01-06 12:00 UTC, barreiro commented on horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java
> +    public static final String[] auths = { NoAuth._TYPE, APIKeyAuth._TYPE, UsernamePassAuth._TYPE };
```suggestion
```

2025-01-06 12:00 UTC, barreiro commented on horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java
> +    public static final Boolean builtIn = false;
```suggestion
```

2025-01-06 12:00 UTC, barreiro commented on horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/CollectorApiDatastoreConfig.java
> +    public static final Boolean builtIn = false;
```suggestion
```

2025-01-06 12:00 UTC, barreiro commented on horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/PostgresDatastoreConfig.java
> +    public static final String[] auths = { NoAuth._TYPE };
```suggestion
```

2025-01-06 12:00 UTC, barreiro commented on horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/PostgresDatastoreConfig.java
> +    public static final Boolean builtIn = true;
```suggestion
```

2025-01-06 12:00 UTC, barreiro commented on horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java
> +                    || "".equals(usernamePassAuth.username) || "".equals(usernamePassAuth.password)) {
```suggestion
            if (usernamePassAuth.username == null || usernamePassAuth.username.isEmpty()
                    || usernamePassAuth.password == null || usernamePassAuth.password.isEmpty()) {
```

2025-01-06 12:00 UTC, barreiro commented on horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java
> +            if ("".equals(apiKeyAuth.apiKey)) {
```suggestion
            if (apiKeyAuth.apiKey == null || apiKeyAuth.apiKey.isEmpty()) {
```

2025-01-06 12:30 UTC, johnaohara commented on horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java
> +    public static final String[] auths = { NoAuth._TYPE, APIKeyAuth._TYPE, UsernamePassAuth._TYPE };
This is accessed via reflection: https://github.com/Hyperfoil/Horreum/pull/2223/files#diff-8a4bd7c5a2730d0b066069e4fe1d81fd44eb3c7f84b69867ad74b83f74aca8deR27-R30

2025-01-06 12:30 UTC, johnaohara commented on horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java
> +    public static final Boolean builtIn = false;
This is accessed via reflection: https://github.com/Hyperfoil/Horreum/pull/2223/files#diff-8a4bd7c5a2730d0b066069e4fe1d81fd44eb3c7f84b69867ad74b83f74aca8deR27-R30

2025-01-06 12:30 UTC, johnaohara commented on horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/CollectorApiDatastoreConfig.java
> +    public static final Boolean builtIn = false;
This is accessed via reflection: https://github.com/Hyperfoil/Horreum/pull/2223/files#diff-8a4bd7c5a2730d0b066069e4fe1d81fd44eb3c7f84b69867ad74b83f74aca8deR27-R30

2025-01-06 12:30 UTC, johnaohara commented on horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/PostgresDatastoreConfig.java
> +    public static final String[] auths = { NoAuth._TYPE };
This is accessed via reflection: https://github.com/Hyperfoil/Horreum/pull/2223/files#diff-8a4bd7c5a2730d0b066069e4fe1d81fd44eb3c7f84b69867ad74b83f74aca8deR27-R30

2025-01-06 12:31 UTC, johnaohara commented on horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java
> +            if ("".equals(apiKeyAuth.apiKey)) {
Thanks for catching this

2025-01-06 14:32 UTC, johnaohara commented on horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/CollectorApiDatastoreConfig.java
> +            if ("".equals(apiKeyAuth.apiKey) || apiKeyAuth.apiKey == null) {
will change to `isBlank()` to take into account white-space as well

2025-01-06 14:32 UTC, johnaohara commented on horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java
> +                    || "".equals(usernamePassAuth.username) || "".equals(usernamePassAuth.password)) {
will change to `isBlank()` to take into account white-space as well

2025-01-07 09:42 UTC, lampajr approved these changes
LGTM!

I added just a minor comment, up to you to include it or not as it would be just a simplification 🚀

2025-01-07 09:42 UTC, lampajr commented on horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/CollectorApiDatastore.java
> +        }
This could be simplified as we are setting `application/json` on both cases
```suggestion
        tagsBuilder
                .header("Content-Type", "application/json");
        if (jsonDatastoreConfig.authentication instanceof APIKeyAuth) {
            tagsBuilder
                    .header("token", ((APIKeyAuth) jsonDatastoreConfig.authentication).apiKey);
        }
```

2025-01-07 16:54 UTC, johnaohara commented on horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/CollectorApiDatastore.java
> +        }
Done, thanks

2025-01-08 16:48 UTC, barreiro commented
I think this one is good to go.

2025-01-08 16:48 UTC, merged