update: quinoa version 1.2.4 to 1.2.5
Hyperfoil/Horreum pull request #412
Opened 2023-03-12 01:01 UTC by shivam-sharma7

update: quinoa version 1.2.4 to 1.2.5

2023-03-12 01:01 UTC, shivam-sharma7 commented
review/ @jesperpedersen

2023-03-12 01:04 UTC, jesperpedersen commented
Whitespace...

2023-03-12 01:08 UTC, shivam-sharma7 commented
> Whitespace...

I did't understand

2023-03-12 01:11 UTC, jesperpedersen commented
You reindented the entire file. Keep the current whitespace spacing, just add the quinoa upgrade and yourself to `<developers>`

2023-03-12 01:19 UTC, shivam-sharma7 commented
> You reindented the entire file. Keep the current whitespace spacing, just add the quinoa upgrade and yourself to `<developers>`

no i just upgrade only quinoa version and add myself as developer but it's automaticaly reflecting as change in whole file.

2023-03-12 01:19 UTC, jesperpedersen commented
Remember to always squash and rebase pull requests.

You can look at https://github.com/Hyperfoil/Horreum/pull/412/files to see your current changes. The changes can only reflect the issue raised.

2023-03-12 01:21 UTC, jesperpedersen commented
It is DOS line feeds - you need to use Unix ones

2023-03-12 01:22 UTC, shivam-sharma7 commented
> Remember to always squash and rebase pull requests.
> 
> You can look at https://github.com/Hyperfoil/Horreum/pull/412/files to see your current changes. The changes can only reflect the issue raised.

I know as reviewer you have to face some problem with these change but I have't touch anything

2023-03-12 01:25 UTC, shivam-sharma7 commented
take your time to review it.

2023-03-12 01:28 UTC, jesperpedersen commented
You need to run a tool like `dos2unix` on it

2023-03-12 01:32 UTC, shivam-sharma7 commented
can we merged it for now?

2023-03-12 01:32 UTC, shivam-sharma7 commented
> You need to run a tool like `dos2unix` on it

thanks

2023-03-12 01:37 UTC, jesperpedersen commented
Pull requests are merged based on minimal changes for the improvement in question. And, squashed and rebased commits is needed.

One improvement - one commit - which is up-to-date

2023-03-12 01:44 UTC, shivam-sharma7 commented
> One improvement - one commit - which is up-to-date

you mean i need to push only one commit instead it' having currently two commits

2023-03-12 01:47 UTC, jesperpedersen commented
Yes, only one commit.

https://www.git-tower.com/learn/git/faq/git-squash - and force push aka `git push -f origin update-quinoa`

2023-03-12 02:02 UTC, shivam-sharma7 commented
> Yes, only one commit.
> 
> https://www.git-tower.com/learn/git/faq/git-squash - and force push aka `git push -f origin update-quinoa`

Thanks Done ✅

2023-03-12 02:07 UTC, jesperpedersen requested changes

2023-03-12 02:07 UTC, jesperpedersen commented on pom.xml
> +            <organization>Red Hat</organization>
Remove

2023-03-12 02:07 UTC, jesperpedersen commented on pom.xml
> +            <organizationUrl>http://www.redhat.com</organizationUrl>
Remove

2023-03-12 02:12 UTC, shivam-sharma7 commented on pom.xml
> +            <organizationUrl>http://www.redhat.com</organizationUrl>
Removed

2023-03-12 02:15 UTC, jesperpedersen commented
... We are back with DOS line feeds ...

2023-03-12 02:19 UTC, shivam-sharma7 commented
> ... We are back with DOS line feeds ...

Done ✅

2023-03-12 02:24 UTC, merged

2023-03-12 02:26 UTC, jesperpedersen commented
Rebased -- please, keep this in mind, and merged.

Thanks for your contribution !

2023-03-12 02:28 UTC, shivam-sharma7 commented
> Rebased -- please, keep this in mind, and merged.
> 
> Thanks for your contribution !

Thanks

2023-03-12 07:28 UTC, shivam-sharma7 commented
> and yourself to `<developers>`

mean?

2023-03-13 06:42 UTC, jesperpedersen commented
You can raise another pull request with

```
  <developer>
      <name>...</name>
      <email>...</email>
  </developer>
```

in `pom.xml`.