Add ConfigService to horreum client
Hyperfoil/Horreum pull request #549
Opened 2023-06-07 09:24 UTC by johnaohara

2023-06-07 12:18 UTC, jesperpedersen requested changes

2023-06-07 12:18 UTC, jesperpedersen commented on horreum-client/src/main/java/io/hyperfoil/tools/HorreumClient.java
> +import io.hyperfoil.tools.horreum.api.services.*;
Lets keep the explicit imports

2023-06-08 13:49 UTC, merged

2023-06-08 13:52 UTC, jesperpedersen commented
Merged to `master` - feel free to open a pull request for `0.7.x` if you need it.

Thanks for your contribution !

2023-06-08 13:58 UTC, johnaohara commented
@jesperpedersen the tests were failing when this was merged. I just pushed another update to split out the ConfigService into interface and impl

2023-06-08 13:58 UTC, johnaohara commented
I'll open another PR that fixes the test failures